### ISSUE TITLE
Website 1.0

### ISSUE THREAD

**Issue by joepavitt** [flowforge/website#203]
### Description

Wrapping epic to cover updates required to the Website ahead of 1.0 Release

### Tasks:

Importance: _High_
- [x] https://github.com/flowforge/website/issues/184
- [x] https://github.com/flowforge/website/issues/199
- [x] https://github.com/flowforge/website/issues/202
- [x] https://github.com/flowforge/website/issues/209

Importance: _Medium_
- [ ] https://github.com/flowforge/website/issues/113
- [ ] https://github.com/flowforge/website/issues/208

Importance: _Low_
- [ ] https://github.com/flowforge/website/issues/194

**Comment by joepavitt** [comment]
High Importance items delivered, all others will move as tasks to iteration 1.1
